CREATE TABLE IF NOT EXISTS `USERS` (
    `ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `EMAIL` VARCHAR(50) NOT NULL COMMENT '사용자 이메일',
    `NAME` VARCHAR(50) NOT NULL COMMENT '사용자 이름',
    `PW` VARCHAR(100) COMMENT '사용자 비밀번호',
    `ACCOUNT_TYPE` VARCHAR(1) NOT NULL DEFAULT 'U' COMMENT '계정 유형',
    `PHONE` VARCHAR(20) COMMENT '사용자 전화번호',
    `PROFILE_IMG` VARCHAR(300) COMMENT '사용자 프로필 이미지',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '사용자 생성일',
    `UPDATED_AT` DATETIME COMMENT '사용자 수정일',
    `DELETED_AT` DATETIME COMMENT '사용자 삭제일',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_USERS_EMAIL` (`EMAIL`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '사용자';

CREATE TABLE IF NOT EXISTS `USER_LIKES` (
    `USER_ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `EVENT_ID` BINARY(16) NOT NULL COMMENT '이벤트 식별자',
    PRIMARY KEY (`USER_ID`, `EVENT_ID`),
    CONSTRAINT `FK_USER_LIKES_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`),
    CONSTRAINT `FK_USER_LIKES_EVENT_ID` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENTS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '사용자 찜 목록';

CREATE TABLE IF NOT EXISTS `EVENTS` (
    `ID` BINARY(16) NOT NULL COMMENT '이벤트 식별자',
    `USER_ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `TITLE` VARCHAR(100) NOT NULL COMMENT '이벤트 제목',
    `DESCRIPTION` LONGTEXT NOT NULL COMMENT '이벤트 상세',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이벤트 생성일',
    `UPDATED_AT` DATETIME COMMENT '이벤트 수정일',
    `DELETED_AT` DATETIME COMMENT '이벤트 삭제일',
    `BOOK_STARTED_AT` DATETIME NOT NULL COMMENT '이벤트 예약 시작일',
    `BOOK_ENDED_AT` DATETIME NOT NULL COMMENT '이벤트 예약 종료일',
    `PLACE_NAME` VARCHAR(100) COMMENT '이벤트 장소 이름',
    `PLACE_ADDRESS` VARCHAR(200) COMMENT '이벤트 장소 주소',
    `MAX_PER_USER` INT NOT NULL DEFAULT 1 COMMENT '사용자당 최대 예약 수',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_EVENTS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '이벤트';

CREATE TABLE IF NOT EXISTS `EVENT_SCHEDULES` (
    `ID` BINARY(16) NOT NULL COMMENT '이벤트 회차 식별자',
    `EVENT_ID` BINARY(16) NOT NULL COMMENT '이벤트 식별자',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '이벤트 회차 생성일',
    `UPDATED_AT` DATETIME COMMENT '이벤트 회차 수정일',
    `DELETED_AT` DATETIME COMMENT '이벤트 회차 삭제일',
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT '이벤트 회차 상태',
    `START_AT` DATETIME NOT NULL COMMENT '이벤트 회차 시작일',
    `END_AT` DATETIME COMMENT '이벤트 회차 종료일',
    `ROUND_NO` INT NOT NULL COMMENT '이벤트 회차 번호',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_EVENT_SCHEDULES_ROUND_NO` (`ROUND_NO`),
    CONSTRAINT `FK_EVENT_SCHEDULES_EVENT_ID` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENTS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '이벤트 회차';

CREATE TABLE IF NOT EXISTS `EVENT_SEAT_GRADES` (
    `ID` BINARY(16) NOT NULL COMMENT '이벤트 좌석 등급 식별자',
    `SCHEDULE_ID` BINARY(16) NOT NULL COMMENT '이벤트 회차 식별자',
    `NAME` VARCHAR(50) NOT NULL COMMENT '좌석 등급 이름',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '좌석 등급 생성일',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '좌석 등급 정렬 순서',
    `TOTAL` INT NOT NULL COMMENT '좌석 등급 전체 수량',
    `PRICE` INT NOT NULL COMMENT '좌석 등급 가격',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_EVENT_SEAT_GRADES_SCHEDULE_ID` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `EVENT_SCHEDULES` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '이벤트 좌석 등급';

CREATE TABLE IF NOT EXISTS `REVIEWS` (
    `ID` BINARY(16) NOT NULL COMMENT '후기 식별자',
    `USER_ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `SCORE` INT(1) NOT NULL COMMENT '후기 점수',
    `CONTENT` TEXT COMMENT '후기 내용',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_REVIEWS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '후기';

CREATE TABLE IF NOT EXISTS `REVIEW_IMGS` (
    `ID` BINARY(16) NOT NULL COMMENT '후기 이미지 식별자',
    `REVIEW_ID` BINARY(16) NOT NULL COMMENT '후기 식별자',
    `IMG_URL` VARCHAR(200) NOT NULL COMMENT '후기 이미지 URL',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '후기 이미지 정렬 순서',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_REVIEW_IMGS_REVIEW_ID` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEWS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '후기 이미지';

CREATE TABLE IF NOT EXISTS `TICKETS` (
    `ID` BINARY(16) NOT NULL COMMENT '티켓 식별자',
    `TICKET_NUMBER` VARCHAR(50) NOT NULL COMMENT '티켓 번호',
    `SCHEDULE_ID` BINARY(16) NOT NULL COMMENT '이벤트 회차 식별자',
    `USER_ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '티켓 생성일',
    `CANCELED_AT` DATETIME COMMENT '티켓 취소일',
    `USED_AT` DATETIME COMMENT '티켓 사용일',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_TICKETS_TICKET_NUMBER` (`TICKET_NUMBER`),
    CONSTRAINT `FK_TICKETS_SCHEDULE_ID` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `EVENT_SCHEDULES` (`ID`),
    CONSTRAINT `FK_TICKETS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '티켓';

CREATE TABLE IF NOT EXISTS `PAYMENTS` (
    `ID` BINARY(16) NOT NULL COMMENT '결제 식별자',
    `TICKET_ID` BINARY(16) NOT NULL COMMENT '티켓 식별자',
    `TOSS_PAYMENT_KEY` VARCHAR(50) NOT NULL COMMENT '토스 결제 식별자',
    `PAYMENT_STATUS` VARCHAR(50) NOT NULL COMMENT '결제 상태',
    `APPROVED_AT` TIMESTAMP COMMENT '결제 승인일',
    `CANCELED_AT` TIMESTAMP COMMENT '결제 취소일',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_PAYMENTS_TOSS_PAYMENT_KEY` (`TOSS_PAYMENT_KEY`),
    CONSTRAINT `FK_PAYMENTS_TICKET_ID` FOREIGN KEY (`TICKET_ID`) REFERENCES `TICKETS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '결제 내역';

CREATE TABLE IF NOT EXISTS `PAYMENT_LOGS` (
    `ID` BINARY(16) NOT NULL COMMENT '결제 로그 식별자',
    `PAYMENT_ID` BINARY(16) NOT NULL COMMENT '결제 식별자',
    `EVENT_TYPE` VARCHAR(50) NOT NULL COMMENT '결제 이벤트 유형',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '결제 로그 생성일',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PAYMENT_LOGS_PAYMENT_ID` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PAYMENTS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '결제 로그';

CREATE TABLE IF NOT EXISTS `CONTACTS` (
    `ID` BINARY(16) NOT NULL COMMENT '문의 식별자',
    `PAR_ID` BINARY(16) COMMENT '상위 문의 식별자',
    `USER_ID` BINARY(16) NOT NULL COMMENT '사용자 식별자',
    `CONTENT` TEXT NOT NULL COMMENT '문의 내용',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '문의 생성일',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_CONTACTS_PAR_ID` FOREIGN KEY (`PAR_ID`) REFERENCES `CONTACTS` (`ID`),
    CONSTRAINT `FK_CONTACTS_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '문의 내역';

CREATE TABLE IF NOT EXISTS `CONTACT_IMGS` (
    `ID` BINARY(16) NOT NULL COMMENT '문의 이미지 식별자',
    `CONTACT_ID` BINARY(16) NOT NULL COMMENT '문의 식별자',
    `IMG_URL` VARCHAR(200) NOT NULL COMMENT '문의 이미지 URL',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '문의 이미지 정렬 순서',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_CONTACT_IMGS_CONTACT_ID` FOREIGN KEY (`CONTACT_ID`) REFERENCES `CONTACTS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '문의 내역 이미지';

CREATE TABLE IF NOT EXISTS `PENALTIES` (
    `ID` BINARY(16) NOT NULL COMMENT '제제 내역 식별자',
    `ADMIN_ID` BINARY(16) NOT NULL COMMENT '제제 처리 관리자 식별자',
    `USER_ID` BINARY(16) NOT NULL COMMENT '제제 대상 사용자 식별자',
    `PAYLOAD` TEXT NOT NULL COMMENT '제제 사유',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '제제 내역 생성일',
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PENALTIES_ADMIN_ID` FOREIGN KEY (`ADMIN_ID`) REFERENCES `USERS` (`ID`),
    CONSTRAINT `FK_PENALTIES_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '제제 내역';
